### PR TITLE
Suggested style update on start page

### PR DESCRIPTION
**Pull request by itbf9**
This PR include:
- New style on start page

Screenshot from 2023-11-13 13-58-44
Screenshot from 2023-11-13 13-59-10

(I would also like to propose that we change lib for the calendar heatmap, the current one is not so nice IMO)

### CODE REVIEW

**Comment by xbenyx** [comment]
Nice is getting better. Did you move the footer to home? Regarding echarts it looks funny in DarkMode, we could use https://swimlane.gitbook.io/ngx-charts/examples/heat-map-chart
or 
https://github.com/plotly/angular-plotly.js/blob/master/README.md

**Comment by itbf9** [comment]
No i did not move the footer, do you mean the bar with "Hashtopolis is available..."? Yes it looks kinda like a footer :)

Regarding heatmap, This looked quite nice as well: https://www.npmjs.com/package/angular-calendar-heatmap

**Comment by xbenyx** [comment]
Ohhh a d3.js directive. I see the project is a little bit abandoned and for the angular component they recommend, https://github.com/g1eb/angular2-calendar-heatmap something that i cannot find is about the darkmode. 

By the way, echarts supports DarkMode theme, 
https://echarts.apache.org/en/download-theme.html

image
image

**Review by xbenyx — APPROVED** [review]
LGTM

**Pull request merged**
