### PR TITLE
Clients + vouchers table and create agent page

### PR DESCRIPTION
**Pull request by itbf9**
This PR includes:
- Updated agent binaries table component
- A new vouchers table component + datasource
- Updated create agent page

Screenshot from 2023-11-23 08-03-46
Screenshot from 2023-11-23 08-04-10
Screenshot from 2023-11-23 08-04-30

### CODE REVIEW

**Comment by xbenyx** [comment]
@itbf9 I like the stepper is an easy way to add more complex steps and add more data without overloading the main page. 

Just wonder what the users prefer, see all data at once as creating a new agent is not usual or go through to some steps.

**Comment by itbf9** [comment]
> Just wonder what the users prefer, see all data at once as creating a new agent is not usual or go through to some steps.

I see your point! But as you said this is not a task you do very often and that's why I think it could be worth an extra click to make it more clear. My though was that it would be nice to add more information on each step to help the user. 

But I have no problems with skipping the steps if that's preferred by the general users :)  I Added screenshots, lets discuss it

**Comment by xbenyx** [comment]
Can this be merged?

**Comment by itbf9** [comment]
Yes i will fix the conflicts

**Pull request merged**
